# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test case validation with SHACL shapes

on:  
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd shapes
        pip install -r requirements.txt
    - name: Run tests
      run: |
        cd shapes
        python3 tests.py -vvv
